package com.sebastianmejia.weather.resources;

public class Countries {
    public static String[][] countries = {
            {"AD", "Andorra", "Andorra"},
            {"AE", "United Arab Emirates", "Emiratos Árabes Unidos"},
            {"AF", "Afghanistan", "Afganistán"},
            {"AG", "Antigua and Barbuda", "Antigua y Barbuda"},
            {"AI", "Anguilla", "Anguila"},
            {"AL", "Albania", "Albania"},
            {"AM", "Armenia", "Armenia"},
            {"AN", "Netherland Antilles", "Antillas holandesas"},
            {"AO", "Angola", "Angola"},
            {"AQ", "Antarctica", "Antártida"},
            {"AR", "Argentina", "Argentina"},
            {"AS", "American Samoa", "Samoa Americana"},
            {"AT", "Austria", "Austria"},
            {"AU", "Australia", "Australia"},
            {"AW", "Aruba", "Aruba"},
            {"AZ", "Azerbaijan", "Azerbaiyán"},
            {"BA", "Bosnia- Herzegovina", "Bosnia y Herzegovina"},
            {"BB", "Barbados", "Barbados"},
            {"BD", "Bangladesh", "Bangladesh"},
            {"BE", "Belgium", "Bélgica"},
            {"BF", "Burkina Faso", "Burkina Faso"},
            {"BG", "Bulgaria", "Bulgaria"},
            {"BH", "Bahrain", "Baréin"},
            {"BI", "Burundi", "Burundi"},
            {"BJ", "Benin", "Benín"},
            {"BM", "Bermuda", "Islas Bermudas"},
            {"BN", "Brunei Darussalam", "Brunei Darussalam"},
            {"BO", "Bolivia", "Bolivia"},
            {"BR", "Brazil", "Brasil"},
            {"BS", "Bahamas", "Bahamas"},
            {"BT", "Bhutan", "Bután"},
            {"BV", "Bouvet Island", "Isla Bouvet"},
            {"BW", "Botswana", "Botsuana"},
            {"BY", "Belarus", "Bielorrusia"},
            {"BZ", "Belize", "Belice"},
            {"CA", "Canada", "Canadá"},
            {"CC", "Cocos (Keeling) Islands", "Islas Cocos (Keeling)"},
            {"CF", "Central African Republic", "República Centroafricana"},
            {"CG", "Congo", "Congo"},
            {"CH", "Switzerland", "Suiza"},
            {"CI", "Ivory Coast", "Costa de Marfil"},
            {"CK", "Cook Islands", "Islas Cook"},
            {"CL", "Chile", "Chile"},
            {"CM", "Cameroon", "Camerún"},
            {"CN", "China", "China"},
            {"CO", "Colombia", "Colombia"},
            {"CR", "Costa Rica", "Costa Rica"},
            {"CS", "Czechoslovakia (obsolete)", "Checoslovaquia (obsoleto)"},
            {"CU", "Cuba", "Cuba"},
            {"CV", "Cape Verde", "Cabo Verde"},
            {"CX", "Christmas Island", "Isla de Navidad"},
            {"CY", "Cyprus", "Chipre"},
            {"CZ", "Czech Republic", "Republica checa"},
            {"DE", "Germany", "Alemania"},
            {"DJ", "Djibouti", "Yibuti"},
            {"DK", "Denmark", "Dinamarca"},
            {"DM", "Dominica", "Dominica"},
            {"DO", "Dominican Republic", "República Dominicana"},
            {"DZ", "Algeria", "Argelia"},
            {"EC", "Ecuador", "Ecuador"},
            {"EE", "Estonia", "Estonia"},
            {"EG", "Egypt", "Egipto"},
            {"EH", "Western Sahara", "Sahara Occidental"},
            {"ER", "Eritrea", "Eritrea"},
            {"ES", "Spain", "España"},
            {"ET", "Ethiopia", "Etiopía"},
            {"FI", "Finland", "Finlandia"},
            {"FJ", "Fiji", "Fiyi"},
            {"FK", "Falkland Isl.( Malvinas)", "Islas Malvinas (Malvinas)"},
            {"FM", "Micronesia", "Micronesia"},
            {"FO", "Faroe Islands", "Islas Faroe"},
            {"FR", "France", "Francia"},
            {"FX", "France (Europe only)", "Francia (solo Europa)"},
            {"GA", "Gabon", "Gabón"},
            {"GB", "Great Britain (UK)", "Gran Bretaña (Reino Unido)"},
            {"GD", "Grenada", "Granada"},
            {"GE", "Georgia", "Georgia"},
            {"GF", "Guyana (Fr.)", "Guayana (Francia)"},
            {"GH", "Ghana", "Ghana"},
            {"GI", "Gibraltar", "Gibraltar"},
            {"GL", "Greenland", "Groenlandia"},
            {"GM", "Gambia", "Gambia"},
            {"GN", "Guinea", "Guinea"},
            {"GP", "Guadeloupe (Fr.)", "Guadalupe (Fr.)"},
            {"GQ", "Equatorial Guinea", "Guinea Ecuatorial"},
            {"GR", "Greece", "Grecia"},
            {"GS", "South Georgia & South Sandwich Islands", "Islas Georgias del Sur y Sandwich del Sur"},
            {"GT", "Guatemala", "Guatemala"},
            {"GU", "Guam (US)", "Guam (Estados Unidos)"},
            {"GW", "Guinea Bissau", "Guinea-Bisáu"},
            {"GY", "Guyana", "Guayana"},
            {"HK", "Hong Kong", "Hong Kong"},
            {"HM", "Heard & McDonald Islands", "Islas Heard y McDonald"},
            {"HN", "Honduras", "Honduras"},
            {"HR", "Croatia", "Croacia"},
            {"HT", "Haiti", "Haití"},
            {"HU", "Hungary", "Hungría"},
            {"ID", "Indonesia", "Indonesia"},
            {"IE", "Ireland", "Irlanda"},
            {"IL", "Israel", "Israel"},
            {"IN", "India", "India"},
            {"IO", "British Indian Ocean Terr.", "Terreno Británico del Océano Índico."},
            {"IQ", "Iraq", "Irak"},
            {"IR", "Iran", "Irán"},
            {"IS", "Iceland", "Islandia"},
            {"IT", "Italy", "Italia"},
            {"JM", "Jamaica", "Jamaica"},
            {"JO", "Jordan", "Jordán"},
            {"JP", "Japan", "Japón"},
            {"KE", "Kenya", "Kenia"},
            {"KG", "Kyrgyz Republic", "República Kirguiza"},
            {"KH", "Cambodia", "Camboya"},
            {"KI", "Kiribati", "Kiribati"},
            {"KM", "Comoros", "Comoras"},
            {"KN", "St. Kitts Nevis Anguilla", "San Cristóbal y Nieves Anguila"},
            {"KP", "Korea (North) ", "Corea (del Norte)"},
            {"KR", "Korea (South)", "Corea del Sur)"},
            {"KW", "Kuwait", "Kuwait"},
            {"KY", "Cayman Islands", "Islas Caimán"},
            {"KZ", "Kazachstan", "Kazajstán"},
            {"LA", "Laos", "Laos"},
            {"LB", "Lebanon", "Líbano"},
            {"LC", "Saint Lucia", "Santa Lucía"},
            {"LI", "Liechtenstein", "Liechtenstein"},
            {"LK", "Sri Lanka", "Sri Lanka"},
            {"LR", "Liberia", "Liberia"},
            {"LS", "Lesotho", "Lesoto"},
            {"LT", "Lithuania", "Lituania"},
            {"LU", "Luxembourg", "Luxemburgo"},
            {"LV", "Latvia", "Letonia"},
            {"LY", "Libya", "Libia"},
            {"MA", "Morocco", "Marruecos"},
            {"MC", "Monaco", "Mónaco"},
            {"MD", "Moldova", "Moldavia"},
            {"MG", "Madagascar", "Madagascar"},
            {"MH", "Marshall Islands", "Islas Marshall"},
            {"MK", "Macedonia (prev. Yug.)", "Macedonia (anterior. Yug.)"},
            {"ML", "Mali", "Malí"},
            {"MM", "Myanmar", "Birmania"},
            {"MN", "Mongolia", "Mongolia"},
            {"MO", "Macau", "Macao"},
            {"MP", "Northern Mariana Islands", "Islas Marianas del Norte"},
            {"MQ", "Martinique (Fr.)", "Martinica (Francia)"},
            {"MR", "Mauritania", "Mauritania"},
            {"MS", "Montserrat", "Montserrat"},
            {"MT", "Malta", "Malta"},
            {"MU", "Mauritius", "Mauricio"},
            {"MV", "Maldives", "Maldivas"},
            {"MW", "Malawi", "Malaui"},
            {"MX", "Mexico", "México"},
            {"MY", "Malaysia", "Malasia"},
            {"MZ", "Mozambique", "Mozambique"},
            {"NA", "Namibia", "Namibia"},
            {"NC", "New Caledonia Fr.", "Nueva Caledonia p."},
            {"NE", "Niger", "Níger"},
            {"NF", "Norfolk Island", "Isla Norfolk"},
            {"NG", "Nigeria", "Nigeria"},
            {"NI", "Nicaragua", "Nicaragua"},
            {"NL", "Netherlands", "Países Bajos"},
            {"NO", "Norway", "Noruega"},
            {"NP", "Nepal", "Nepal"},
            {"NR", "Nauru", "Nauru"},
            {"NU", "Niue", "Niue"},
            {"NZ", "New Zealand", "Nueva Zelanda"},
            {"OM", "Oman", "Omán"},
            {"PA", "Panama", "Panamá"},
            {"PE", "Peru", "Perú"},
            {"PF", "Polynesia (Fr.)", "Polinesia (Francia)"},
            {"PG", "Papua New Guinea", "Papúa Nueva Guinea"},
            {"PH", "Philippines", "Filipinas"},
            {"PK", "Pakistan", "Pakistán"},
            {"PL", "Poland", "Polonia"},
            {"PM", "St. Pierre & Miquelon", "San Pedro y Miquelón"},
            {"PN", "Pitcairn", "pitcairn"},
            {"PR", "Puerto Rico (US)", "Puerto Rico (Estados Unidos)"},
            {"PT", "Portugal", "Portugal"},
            {"PW", "Palau", "palaos"},
            {"PY", "Paraguay", "Paraguay"},
            {"QA", "Qatar", "Katar"},
            {"RE", "Reunion (Fr.)", "Reunión (Fr.)"},
            {"RO", "Romania", "Rumania"},
            {"RU", "Russian Federation", "Federación Rusa"},
            {"RW", "Rwanda", "Ruanda"},
            {"SA", "Saudi Arabia", "Arabia Saudita"},
            {"SB", "Solomon Islands", "Islas Salomón"},
            {"SC", "Seychelles", "Seychelles"},
            {"SD", "Sudan", "Sudán"},
            {"SE", "Sweden", "Suecia"},
            {"SG", "Singapore", "Singapur"},
            {"SH", "St. Helena", "Santa Elena"},
            {"SI", "Slovenia", "Eslovenia"},
            {"SJ", "Svalbard& Jan Mayen Islands", "Islas Svalbard y Jan Mayen"},
            {"SK", "Slovakia (Slovak Republic)", "Eslovaquia (República Eslovaca)"},
            {"SL", "Sierra Leone", "Sierra Leona"},
            {"SM", "San Marino", "San Marino"},
            {"SN", "Senegal", "Senegal"},
            {"SO", "Somalia", "Somalia"},
            {"SR", "Suriname", "Surinam"},
            {"ST", "St. Tome and Principe", "Santo Tomé y Príncipe"},
            {"SU", "Soviet Union (obsolete)", "Unión Soviética (obsoleta)"},
            {"SV", "El Salvador", "El Salvador"},
            {"SY", "Syria", "Siria"},
            {"SZ", "Swaziland", "Suazilandia"},
            {"TC", "Turks& Caicos Islands", "Islas Turcas y Caicos"},
            {"TD", "Chad", "Chad"},
            {"TF", "French Southern Territory", "Territorio Austral Francés"},
            {"TG", "Togo", "Togo"},
            {"TH", "Thailand", "Tailandia"},
            {"TJ", "Tadjikistan", "Tayikistán"},
            {"TK", "Tokelau", "Tokelau"},
            {"TM", "Turkmenistan", "Turkmenistán"},
            {"TN", "Tunisia", "Túnez"},
            {"TO", "Tonga", "Tonga"},
            {"TP", "East Timor", "Timor Oriental"},
            {"TR", "Turkey", "Turquía"},
            {"TT", "Trinidad Tobago", "Trinidad y Tobago"},
            {"TV", "Tuvalu", "Tuvalu"},
            {"TW", "Taiwan", "Taiwán"},
            {"TZ", "Tanzania", "Tanzania"},
            {"UA", "Ukraine", "Ucrania"},
            {"UG", "Uganda", "Uganda"},
            {"UK", "United Kingdom", "Reino Unido"},
            {"UM", "US Minor outlying Islands", "Islas periféricas menores de EE. UU."},
            {"US", "United States", "Estados Unidos"},
            {"UY", "Uruguay", "Uruguay"},
            {"UZ", "Uzbekistan", "Uzbekistán"},
            {"VA", "Vatican City State", "Estado de la Ciudad del Vaticano"},
            {"VC", "St. Vincent& Grenadines", "San Vicente y las Granadinas"},
            {"VE", "Venezuela", "Venezuela"},
            {"VG", "VirginIslands (GB)", "Islas Vírgenes (GB)"},
            {"VI", "Virgin Islands (US)", "Islas Vírgenes (EE. UU.)"},
            {"VN", "Vietnam", "Vietnam"},
            {"VU", "Vanuatu", "Vanuatu"},
            {"WF", "Wallis & Futuna Islands", "Islas Wallis y Futuna"},
            {"WS", "Samoa", "Samoa"},
            {"YE", "Yemen", "Yemen"},
            {"YT", "Mayotte", "Mayotte"},
            {"YU", "Yugoslavia", "Yugoslavia"},
            {"ZA", "South Africa", "Sudáfrica"},
            {"ZM", "Zambia", "Zambia"},
            {"ZR", "Zaire", "Zaire"},
            {"ZW", "Zimbabwe", "Zimbabue"}
    };

    public static String getNameByISOCode(String countryISOCode, String language) {
        int indexLang = (language.equalsIgnoreCase("en") ? 1 : 2);

        for (String[] country : countries) {
            if (countryISOCode.equalsIgnoreCase(country[0])) {
                return country[indexLang];
            }
        }

        return null;
    }

    public static String getISOCodeByName(String countryName, String language) {
        int indexLang = (language.equalsIgnoreCase("en") ? 1 : 2);

        for (String[] country : countries) {
            if (countryName.equalsIgnoreCase(country[indexLang])) {
                return country[0];
            }
        }

        return null;
    }


    public static String[] getCountryNames(String language){
        int indexLang = (language.equalsIgnoreCase("en") ? 1 : 2);
        String[] countryNames = new String[countries.length];

        for (int k = 0; k < countryNames.length; k++) {
            countryNames[k] = countries[k][indexLang];
        }

        return countryNames;
    }
}
